name: Sync Server Folder to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync backend files and Space config to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git clone https://lakayaka:$HF_TOKEN@huggingface.co/spaces/lakayaka/computershop hf_space

          find hf_space -maxdepth 1 ! -name 'hf_space' ! -name '.git' -exec rm -rf {} +

          cp -r hf-backend hf_space/
          cp README.md Dockerfile hf_space/

          cd hf_space
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy backend update from GitHub Actions"
          git push origin main --force